name: daily-summary

on:
  schedule:
    - cron: "10 21 * * 1-5"
  workflow_dispatch: {}

env:
  OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Daily summary handled by session-summary. ✅"
