name: heartbeat

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

env:
  OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Heartbeat OK $(date -u). ✅"
