name: keepalive

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}

env:
  OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Keepalive OK. ✅"
