name: oanda-bot

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes (UTC)
  workflow_dispatch: {}      # allow manual runs

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      INTERVAL: '1m'
      EXPIRY_MIN: '5'
      MIN_SCORE: '1'
      RSI_BUY: '40'
      RSI_SELL: '60'
      MUST_TRADE: '1'
      USE_TREND: '1'
      PYTHONUNBUFFERED: '1'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          pip install pandas pandas_ta requests pyyaml

      - name: Run bot (with retry, capture logs)
        env:
          OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
          OANDA_ENV: practice
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -e
          mkdir -p logs
          tries=0
          until [ $tries -ge 3 ]; do
            python oanda_signal_bot.py 2>&1 | tee logs/run.log && break
            tries=$((tries+1))
            echo "Retry $tries/3 in 10s..." | tee -a logs/run.log
            sleep 10
          done

          echo "### OANDA Bot Run ($(date -u +'%F %T UTC'))" >> $GITHUB_STEP_SUMMARY
          tail -n 80 logs/run.log >> $GITHUB_STEP_SUMMARY

      - name: Upload run log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: oanda-runlog-${{ github.run_number }}
          path: logs/run.log
          retention-days: 14
