name: oanda-test

on:
  workflow_dispatch: {}

env:
  OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python - <<'PY'
        import os, requests
        key = os.getenv("OANDA_API_KEY")
        print("Has key:", bool(key))
        PY
