name: refresh-assets

on:
  workflow_dispatch: {}          # manual button
  schedule:
    - cron: "0 9 * * 1"          # Mondays 09:00 UTC

permissions:
  contents: write

env:
  OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: " 3.11 "
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install deps
        run: pip install requests pyyaml
      - name: Run refresh
        run: |
          if [ ! -f refresh_assets.py ]; then
            echo "refresh_assets.py missing. Commit it to the repo root."; exit 1
          fi
          python refresh_assets.py
      - name: Commit updated symbols.yaml
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name  "assets-bot"
          git add symbols.yaml || true
          git diff --staged --quiet && echo "No changes" || git commit -m "refresh: update symbols.yaml"
          git push || true