name: refresh-assets

on:
  schedule:
    - cron: "17 9 * * *"   # daily at 09:17 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: |
          python -m pip install --upgrade pip
          python -m pip install requests pyyaml

      - name: Refresh symbols.yaml from Pocket Option
        run: |
          python refresh_assets.py
          echo "------- symbols.yaml preview -------"
          head -n 40 symbols.yaml || true
          echo "------------------------------------"

      - name: Commit changes (if any)
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name  "assets-bot"
          git add symbols.yaml
          git diff --quiet && echo "No changes" || (git commit -m "chore: refresh symbols from Pocket Option" && git push)
