name: Signals (every minute)

on:
  schedule:
    - cron: "* * * * *"   # every minute, UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      MUST_TRADE: "0"
      SUPPRESS_EMPTY: "1"
      INTERVAL: "1m"
      EXPIRY_MIN: "5"
      OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
      OANDA_ENV:     ${{ secrets.OANDA_ENV }}     # "practice" or "live"
      FX_HOURS_UTC:        "0700-1700"
      COMMODITY_HOURS_UTC: "0700-1700"
      INDEX_HOURS_UTC:     "1330-2000"
      STOCK_HOURS_UTC:     "1330-2000"
      WEEKDAYS_FX:         "12345"
      WEEKDAYS_COMMODITY:  "12345"
      WEEKDAYS_INDEX:      "12345"
      WEEKDAYS_STOCK:      "12345"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt

      - name: Run and send signals
        run: python run_and_send.py
