name: Run Signals Bot

on:
  schedule:
    - cron: "*/5 * * * 1-5"  # every 5 min Mon–Fri
  workflow_dispatch: {}
  push:
    paths:
      - 'symbols.yaml'
      - '.github/workflows/run.yml'

jobs:
  run-signals:
    runs-on: ubuntu-latest

    env:
      MUST_TRADE: "0"
      SUPPRESS_EMPTY: "1"
      INTERVAL: "1m"
      EXPIRY_MIN: "5"
      OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
      OANDA_ENV: ${{ secrets.OANDA_ENV }}   # "practice" or "live"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show repo root & file exists
        run: |
          pwd
          ls -lah
          python -c "import sys; print('PYTHONPATH=', sys.path)"
          python -c "import telegram_send; print('telegram_send import OK')"

      - name: Run signals (ensure repo on PYTHONPATH)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python signals_live.py