name: oanda-signals

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch: {}      # allow manual run

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      INTERVAL: "1m"
      EXPIRY_MIN: "5"
      MIN_SCORE: "1"
      RSI_BUY: "40"
      RSI_SELL: "60"
      MUST_TRADE: "1"
      OANDA_ENV: "practice"
      OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install pandas pandas_ta requests pyyaml

      - name: Run OANDA bot
        run: python oanda_signal_bot.py
