name: signals

on:
  schedule:
    - cron: "*/1 * * * *"
    - cron: "*/1 * * * 1-5"   # every 1 minute, weekdays
  schedule:
    - cron: "*/1 * * * *"
  scalper:
    runs-on: ubuntu-latest
  schedule:
    - cron: "*/1 * * * *"
          python-version: "3.11"
  schedule:
    - cron: "*/1 * * * *"
