name: signals

on:
  # allow pushing CSV updates
permissions:
  contents: write
  schedule:
    - cron: "*/5 * * * *"      # generate + evaluate every 5m
  workflow_dispatch: {}

env:
  OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_FREE:  ${{ secrets.TELEGRAM_CHAT_FREE }}
  TELEGRAM_CHAT_BASIC: ${{ secrets.TELEGRAM_CHAT_BASIC }}
  TELEGRAM_CHAT_PRO:   ${{ secrets.TELEGRAM_CHAT_PRO }}
  TELEGRAM_CHAT_VIP:   ${{ secrets.TELEGRAM_CHAT_VIP }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Run signals
        run: python signals.py
      - name: Commit signal log
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "signals-bot"
          mkdir -p data
  git add -A data || true
          git commit -m "update signals $(date -u +'%F %T')" || echo "no changes"
          git push
  evaluate:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Evaluate outcomes
        run: python evaluate.py
      - name: Commit performance updates
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "signals-bot"
          mkdir -p data
  git add -A data || true
          git commit -m "evaluate outcomes $(date -u +'%F %T')" || echo "no changes"
          git push
