name: Run Signals Bot

on:
  schedule:
    - cron: "*/5 * * * 1-5"  # every 5 min Mon–Fri
  workflow_dispatch: {}

jobs:
  run-signals:
    runs-on: ubuntu-latest

    env:
      MUST_TRADE: "0"
      SUPPRESS_EMPTY: "1"
      INTERVAL: "5m"
      EXPIRY_MIN: "10"
      OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
      OANDA_ENV: ${{ secrets.OANDA_ENV }}   # "practice" or "live"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run signals
        run: python signals_live.py
