name: session-summary

on:
  schedule:
    - cron: "5 21 * * 1-5"    # 21:05 UTC Mon–Fri
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: " 3.11 "
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        env:
  OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
        env:  OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_NO_PYTHON_VERSION_WARNING: "1"
        run: |
          pip install pandas requests

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install --upgrade pip
          pip install -r requirements.txt -c constraints.txt