name: stats-bot

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"

env:
  OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Stats bot placeholder. ✅"
