name: stats-bot
on:
  schedule:
    - cron: "*/2 * * * *"   # every 2 minutes
  workflow_dispatch: {}
env:
  OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: python -m pip install --upgrade pip
      - run: pip install requests pyyaml
      - name: Handle /stats commands
        env:
  OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
        env:  OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python stats_bot.py
      - name: Persist offset & counts (if changed)
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name  "signals-bot"
          git add data/updates.offset data/tier_counts.json || true
          git commit -m "stats-bot: persist offsets/counters [skip ci]" || echo "no changes"
          git push || true