name: vip-tally

on:
  schedule:
    - cron: "*/30 * * * 1-5"  # every 30m on weekdays
    - cron: "5 21 * * 1-5"    # 21:05 UTC end-of-session, weekdays
  workflow_dispatch: {}

permissions:
  contents: read

env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_FREE:  ${{ secrets.TELEGRAM_CHAT_FREE }}
  TELEGRAM_CHAT_BASIC: ${{ secrets.TELEGRAM_CHAT_BASIC }}
  TELEGRAM_CHAT_PRO:   ${{ secrets.TELEGRAM_CHAT_PRO }}
  TELEGRAM_CHAT_VIP:   ${{ secrets.TELEGRAM_CHAT_VIP }}

jobs:
  post-tally:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pyyaml
      - name: Broadcast VIP tally to all channels
        env:
          TELEGRAM_BOT_TOKEN: ${{ env.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_FREE:  ${{ env.TELEGRAM_CHAT_FREE }}
          TELEGRAM_CHAT_BASIC: ${{ env.TELEGRAM_CHAT_BASIC }}
          TELEGRAM_CHAT_PRO:   ${{ env.TELEGRAM_CHAT_PRO }}
          TELEGRAM_CHAT_VIP:   ${{ env.TELEGRAM_CHAT_VIP }}
        run: python scripts/post_summary.py
